### PR TITLE
Fix result length in case of empty results

### PR DESCRIPTION
**Pull request by pieterprovoost**
`wm_records_names()` and `wm_records_taxamatch()` will by design throw an error when none of the input names have any results, which is often not desirable because distinguishing this from actual errors (4xx and 5xx) involves parsing HTTP error codes out of the error message. A workaround for this is to pass `on_error = warning`. However, in that case the functions will return a single empty tibble instead of a list of tibbles with a length matching that of the input vector (as indicated in `@return`). This PR ensures that these functions always return a list.

### Current behaviour

```r
> wm_records_names("Abra", on_error = warning)
[[1]]
# A tibble: 1 × 27
  AphiaID url     scientificname authority status unacceptreason taxonRankID rank  valid_AphiaID valid_name
    <int> <chr>   <chr>          <chr>     <chr>  <lgl>                <int> <chr>         <int> <chr>     
1  138474 https:… Abra           Lamarck,… accep… NA                     180 Genus        138474 Abra      
# ℹ 17 more variables: valid_authority <chr>, parentNameUsageID <int>, kingdom <chr>, phylum <chr>,
#   class <chr>, order <chr>, family <chr>, genus <chr>, citation <chr>, lsid <chr>, isMarine <int>,
#   isBrackish <lgl>, isFreshwater <lgl>, isTerrestrial <lgl>, isExtinct <lgl>, match_type <chr>,
#   modified <chr>

> wm_records_names(c("Abra", "xxx"), on_error = warning)
[[1]]
# A tibble: 1 × 27
  AphiaID url     scientificname authority status unacceptreason taxonRankID rank  valid_AphiaID valid_name
    <int> <chr>   <chr>          <chr>     <chr>  <lgl>                <int> <chr>         <int> <chr>     
1  138474 https:… Abra           Lamarck,… accep… NA                     180 Genus        138474 Abra      
# ℹ 17 more variables: valid_authority <chr>, parentNameUsageID <int>, kingdom <chr>, phylum <chr>,
#   class <chr>, order <chr>, family <chr>, genus <chr>, citation <chr>, lsid <chr>, isMarine <int>,
#   isBrackish <lgl>, isFreshwater <lgl>, isTerrestrial <lgl>, isExtinct <lgl>, match_type <chr>,
#   modified <chr>

[[2]]
# A tibble: 0 × 0

> wm_records_names("xxx", on_error = warning)
# A tibble: 0 × 0

Warning message:
(204) No Content - AphiaRecordsByNames 

> wm_records_names(c("xxx", "yyy"), on_error = warning)
# A tibble: 0 × 0

Warning message:
(204) No Content - AphiaRecordsByNames
```

### New behaviour:

```r
> wm_records_names("Abra", on_error = warning)
[[1]]
# A tibble: 1 × 27
  AphiaID url     scientificname authority status unacceptreason taxonRankID rank  valid_AphiaID valid_name
    <int> <chr>   <chr>          <chr>     <chr>  <lgl>                <int> <chr>         <int> <chr>     
1  138474 https:… Abra           Lamarck,… accep… NA                     180 Genus        138474 Abra      
# ℹ 17 more variables: valid_authority <chr>, parentNameUsageID <int>, kingdom <chr>, phylum <chr>,
#   class <chr>, order <chr>, family <chr>, genus <chr>, citation <chr>, lsid <chr>, isMarine <int>,
#   isBrackish <lgl>, isFreshwater <lgl>, isTerrestrial <lgl>, isExtinct <lgl>, match_type <chr>,
#   modified <chr>

> wm_records_names(c("Abra", "xxx"), on_error = warning)
[[1]]
# A tibble: 1 × 27
  AphiaID url     scientificname authority status unacceptreason taxonRankID rank  valid_AphiaID valid_name
    <int> <chr>   <chr>          <chr>     <chr>  <lgl>                <int> <chr>         <int> <chr>     
1  138474 https:… Abra           Lamarck,… accep… NA                     180 Genus        138474 Abra      
# ℹ 17 more variables: valid_authority <chr>, parentNameUsageID <int>, kingdom <chr>, phylum <chr>,
#   class <chr>, order <chr>, family <chr>, genus <chr>, citation <chr>, lsid <chr>, isMarine <int>,
#   isBrackish <lgl>, isFreshwater <lgl>, isTerrestrial <lgl>, isExtinct <lgl>, match_type <chr>,
#   modified <chr>

[[2]]
# A tibble: 0 × 0

> wm_records_names("xxx", on_error = warning)
[[1]]
# A tibble: 0 × 0

Warning message:
(204) No Content - AphiaRecordsByNames 

> wm_records_names(c("xxx", "yyy"), on_error = warning)
[[1]]
# A tibble: 0 × 0

[[2]]
# A tibble: 0 × 0

Warning message:
(204) No Content - AphiaRecordsByNames 
```

### CODE REVIEW

**Comment by pieterprovoost** [comment]
@bart-v Thanks! Any chance we can get a CRAN release with these changes?

**Comment by bart-v** [comment]
I'm not familiar enough with the procedure https://devguide.ropensci.org/releasing.html
Maybe @salvafern can jump in?

**Comment by salvafern** [comment]
Submitted to CRAN

**Comment by salvafern** [comment]
Package updated on CRAN

**Comment by pieterprovoost** [comment]
Great, thanks!

**Pull request merged**
